[book]
title = "mdbook-clash example"
authors = ["Clash contributors"]
src = "src"

[preprocessor.clash]
command = "cargo run --manifest-path ../Cargo.toml --"
clash-cmd = ["clash"]
keep-artifacts = true
